### ISSUE TITLE
[BUG] vidsrcto and vidsrcme and vadapav all stoped working

### ISSUE THREAD

**Issue by EbanNox** [JDALab/mov-cli-films#10]
Vidsrcto returns eather a unicodeDecodeError: utf-8
And same with vidsrcme. They must have changed something on there end to fasilitate this
Vadapav as mentioned in the other issue might stop supporting it self in various ways, but besides the point... the method to search query with this scraper returns error message where the main scraper function between mov-cli and vadapav is broken... vadapav need to be updated with the current mov-cli version to get it working egain

**Comment by EbanNox** [comment]
Issues references to this one
https://github.com/JDALab/mov-cli-films/issues/9#issue-2223126572
https://github.com/JDALab/mov-cli-films/issues/7#issue-2216467306

**Comment by EbanNox** [comment]
Nvm vidsrcme , it's working egain... it had a period where no mater the query, it would throw an error where it is unable to read sertain position of a string. But it is working fine now

**Comment by r3tr0ananas** [comment]
I am currently working on vidsrc.to

**Comment by r3tr0ananas** [comment]
Should be fixed. Try again

**Comment by THEGOLDENPRO** [comment]
yeah latest version of vidsrcto works now. 👍

**Comment by Mopele** [comment]
can you publish it as a new release, so that we can use pip to update?

**Comment by r3tr0ananas** [comment]
You can use pip to update it
