### ISSUE TITLE
Do not remove vidsrcto

### ISSUE THREAD

**Issue by EbanNox** [JDALab/mov-cli-films#14]
In the current uppdate , the vidsrcto was removed from listing but still exists...
I forked and re listed it, and it works just fine...

The only thing not working for me funny enugf is vidsrcme ...

**Comment by r3tr0ananas** [comment]
Why does everything break and fix it self again.

![giphy](https://github.com/JDALab/mov-cli-films/assets/132799819/ee49349b-bf7a-4e4d-b77c-92de260327c1)

**Comment by EbanNox** [comment]
> Why does everything break and fix it self again.
> 
> ![1920x1080_cmsv2_ef1e318f-1250-59cd-a009-e831e7b26503-7512512](https://private-user-images.githubusercontent.com/132799819/321042884-4ec1a2dc-7fa5-4de6-ab16-5b56a0d6b4ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mzg4NTQsIm5iZiI6MTcxMjczODU1NCwicGF0aCI6Ii8xMzI3OTk4MTkvMzIxMDQyODg0LTRlYzFhMmRjLTdmYTUtNGRlNi1hYjE2LTViNTZhMGQ2YjRjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwODQyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWY0MWI5ZWRkMDQxYmIxODQ4MzA3ZWNhYzMxNGU4YmY1N2ZlNzU3OGU3MjMwZGQwZjFiZDk3ZjZhNzhmMzZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n6zqB5XxxF4s_2H8sWFMJuu3rbNk8qulakBMIS0Mr1E)

I know, it's funny 😁
