### ISSUE TITLE
Season and Episode selection not working

### ISSUE THREAD

**Issue by Stel0r** [JDALab/mov-cli-films#15]
no matter wich season or episode is selected on any series the scraper is always returning S01E01

how to recreate
mov-cli -s films regular show (regular show is just an example any series is having this issue)
select any season and episode other than S01 E01

expected behaviour: the Episode selected from the season selected is played

Actual behaviour: S01 E01 is played (in case of regular show is the ep "the power")

**Comment by r3tr0ananas** [comment]
I can't recreate this issue.

**Comment by Stel0r** [comment]
what could have caused this, i've try it on 3 different machines all same installation and all run into the same issue, a dependency problem, whenever i downgrade mov-cli-films to 1.3.3 it stops happening so im unaware of whats causing it

**Comment by Stel0r** [comment]
if i fork this rep how could i add my fork so my mov-cli could use it, im kind of new to collaborating lol sorry

**Comment by r3tr0ananas** [comment]
> if i fork this rep how could i add my fork so my mov-cli could use it, im kind of new to collaborating lol sorry

first you have to clone it and then `cd` in to the folder and use `pip install .`, if you want to install forked version of [mov-cli-films](https://github.com/JDALab/mov-cli-films)

**Comment by Stel0r** [comment]
alright tys ill check what might've caused it tys

**Comment by EbanNox** [comment]
Or u can use the git in pip to install it direcly from github without cloning. Ex:
```
pip install git+https://github.com/EbanNox/mov-cli-films

**Comment by Stel0r** [comment]
well after messign around a bit i checked that the scraper giving me issues is vidsrcme and that the search method on the scraper when calling get_embed is passing a new EpisodeSelector that always requests E01 S01

**Comment by THEGOLDENPRO** [comment]
> well after messign around a bit i checked that the scraper giving me issues is vidsrcme and that the scrape method on the scraper when calling get_embed is passing a new EpisodeSelector that always requests E01 S01

Can you link that line? I think I may have noticed something like that too.

**Comment by THEGOLDENPRO** [comment]
Latest version seems to be working fine, I'm having difficulty reproducing it. I think you may have been on the older plugin with vidsrcto or me as default scraper, that may very well be having episode problems. 

Upgrade to the latest version and try again.

**Comment by THEGOLDENPRO** [comment]
Yeah vidsrcme has that problem it seems.

**Comment by THEGOLDENPRO** [comment]
😭episode needed to be passed there

**Comment by THEGOLDENPRO** [comment]
I'll fix this soon but there vidsrcme seems to be broken atm so for now use another scraper.

**Comment by THEGOLDENPRO** [comment]
Fixed. https://github.com/JDALab/mov-cli-films/commit/b87a3eddd123400866ecf375771e93a86850909a
