### ISSUE TITLE
Tmdb and vidsrcto inconsistency.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [JDALab/mov-cli-films#6]
This is an issue I'm continuing from my comments in #5.

It looks like tmdb episodes are not matching with what's available on vidsrcto.

Like this will error for some reason despite tvmd stating the episode exists:
```sh
mov-cli -c 1 -ep 1:2 -s films Kurulus osman --debug
```
and with `air crash investigation` aka "Mayday" episodes that are not listed in tmdb stream no problem but **some** in later seasons fail to stream. https://www.themoviedb.org/tv/90-mayday/seasons?language=en-GB

This is listed but doesn't stream:
```sh
mov-cli -c 2 -s films air crash investigation --episode 3:22 --debug
```

This is **not** listed but does stream:
```sh
mov-cli -c 2 -s films air crash investigation --episode 15:3 --debug
```

This one is listed but seems to be playing the wrong episode (this could just be a vidsrcto problem though):
```sh
mov-cli -c 2 -s films air crash investigation --episode 4:10 --debug
```

These issues continue to be constant.

**Comment by THEGOLDENPRO** [comment]
yeah seems to be a problem with vidsrcto

**Comment by THEGOLDENPRO** [comment]
I think the scraper is functioning fine. Just some problems on vidsrcto's and vidsrcme's end.

**Comment by r3tr0ananas** [comment]
You could search with IMDb, and then there is an API call that basically turns the IMDb ID into a TMDb ID: `https://api.themoviedb.org/3/find/tt0386950?api_key=###&external_source=imdb_id`.

**Comment by THEGOLDENPRO** [comment]
I later found out that it's just vidsrc not having the episodes available and the issue I had with air crash investigation where an episode that wasn't listed streamed was just a mov-cli bug that I [fixed](https://github.com/mov-cli/mov-cli/commit/d2029bc0dcfea3d67ac5e49ddcfe14ee5e858ac2) where it didn't display the last episode 😐

So I think the solution now is to have the scraper check how many episodes are available and set that value to be returned in scrape episodes instead of the value from tmdb.

**Comment by THEGOLDENPRO** [comment]
This will improve things significantly like the commits I added to only display available media. I think we should phase out the media not found exception, it's hurting UX.

**Comment by THEGOLDENPRO** [comment]
![SvEv](https://github.com/JDALab/mov-cli-films/assets/66202304/36490a6c-97bd-4bd1-8a27-23098f47c4ce)

**Comment by r3tr0ananas** [comment]
> ![SvEv](https://private-user-images.githubusercontent.com/66202304/321045513-36490a6c-97bd-4bd1-8a27-23098f47c4ce.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTE4MjgsIm5iZiI6MTcxMjcxMTUyOCwicGF0aCI6Ii82NjIwMjMwNC8zMjEwNDU1MTMtMzY0OTBhNmMtOTdiZC00YmQxLThhMjctMjMwOThmNDdjNGNlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAxMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZGFjZjg3ZDQwYTk1YzllNTA2OGQyYWNlMzg0MWJmYmFmZWQ3NzljZTNjYjkzYzU5ZmEyYjhjMzBmNGNkZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7sUH5jZ0AWbSr00RkPHg3q4nu76G4pbN7WifLCF1-Mg)

![2419a112-bf6a-4825-8a18-d9c115ebbe1d-small](https://github.com/JDALab/mov-cli-films/assets/132799819/74dfc7b9-a4a8-4931-b5f0-51dd7cb73606)

**Comment by THEGOLDENPRO** [comment]
it's 3am don't question it

**Comment by r3tr0ananas** [comment]
![image](https://github.com/JDALab/mov-cli-films/assets/132799819/e0857c00-fdf4-4893-98a1-a258306d6d23)

it isn't better for me
